### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#1]
Hello,

I would be greatly interested to implementing such a module into my project, but before doing so I would like to know in how far you are thinking to keep this component up to date and continue work on it?

And would it also be possible to create some kind of documentation?

Thanks and Greetings

**Comment by quentin-ol** [comment]
Hello @FallenRiteMonk , 

To be honest, I don't know how long I will be able to keep it up-to-date. I'm developing this module because of a GUI application that shows the positions of in-the-field devices. This application is part of a bigger project named Sensorlab2 that we'll keep on working for a while so I expect to be maintaining this for at least a year.

My plan for this module is to push as many of Openlayers features (pun not intended) as possible and, eventually, transfer the repository to the Openlayers organization if they're interested.
Obviously, contributions are welcome and I'd gladly help anyone willing to use it.

+1 for documentation, I will get some examples ready. 
Tests are also lacking if anyone is willing to help.

Best regards.

Quentin

Note: I've also developed an equivalent for Angular 1.5 if that's of interest: 
https://github.com/Orange-OpenSource/angular-openlayers

**Comment by alienlike** [comment]
I'm also eager to see some docs and examples. I intend to use OL with Angular 2 on several upcoming projects and may even be able to contribute to this project.

**Comment by quentin-ol** [comment]
Work in progress.

**Comment by quentin-ol** [comment]
Documentation is available in /documentation. Closing as there is now a documentation.
Please open a new issue if the documentation lacks clarity or is misleading
