### ISSUE TITLE
Source format implementation

### ISSUE THREAD

**Issue by achimha** [quentin-ol/angular2-openlayers#41]
I have a semi-working implementation of `ol.source.VectorTile` which requires the parameter `format` in its constructor (unfortunately no `setFormat` available). The format can be something like `ol.format.MVT` which means we would desire this:

```
<aol-source-vectortile>
    <aol-format-mvt></aol-format-mvt>
</aol-source-vectortile>
```

Now this has a chicken and egg problem. In `ngOnInit`, we create the OL3 objects but at this point the child components are not created yet and also they generally assume they can call the parent.

Any suggestion how to model this case?

**Comment by achimha** [comment]
Same is true for the `tileGrid` -- has to be set at object creation time: http://openlayers.org/en/latest/apidoc/ol.source.VectorTile.html

**Comment by quentinlampin** [comment]
I believe the key to your issue is that Angular2 components are created in a top-down manner, meaning containers first. In your case, you need a child component instance to create the container instance. 

The afterContent/View hooks should address this need: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#aftercontent.

Keep me updated, in case I can help (not much spare time at the moment though).

**Comment by achimha** [comment]
Yes, using `afterContentInit` solves the problem. See my latest PR, I've used that approach.
