### ISSUE TITLE
No provider for SourceVectorComponent

### ISSUE THREAD

**Issue by bagasprakarso** [quentin-ol/angular2-openlayers#60]
When i try implementing this code

```
<aol-map [width]="'100%'">
    <aol-view [zoom]="4.98">
       <aol-coordinate [x]="118.015776" [y]="-2.600029" [srid]="'EPSG:4326'"></aol-coordinate>
    </aol-view>

    <aol-layer-tile>
        <aol-source-osm></aol-source-osm>
    </aol-layer-tile>

    <aol-feature>
        <aol-geometry-point>
            <aol-coordinate [x]="5" [y]="45" [srid]="'EPSG:4326'"></aol-coordinate>
        </aol-geometry-point>
        <aol-style>
            <aol-style-circle [radius]="10">
                <aol-style-stroke [color]="'black'" [width]="2"></aol-style-stroke>
                <aol-style-fill [color]="'green'"></aol-style-fill>
            </aol-style-circle>
        </aol-style>
    </aol-feature>

</aol-map>
```

i've got this error

> No provider for SourceVectorComponent!

Can you guys help me about it?

Thanks

**Comment by quentinlampin** [comment]
Hey,
'''aol-features''' must be inserted in an '''aol-source-vector''' which itself is in a '''aol-layer-vector'''.
Have fun with angular2-openlayers

Quentin
-------- Message d'origine --------De : bagasprakarso <notifications@github.com> Date : 11/04/2017  05:19  (GMT+01:00) À : quentin-ol/angular2-openlayers <angular2-openlayers@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [quentin-ol/angular2-openlayers] No provider for SourceVectorComponent (#60) 
When i try implementing this code
<aol-map [width]="'100%'">
    <aol-view [zoom]="4.98">
       <aol-coordinate [x]="118.015776" [y]="-2.600029" [srid]="'EPSG:4326'"></aol-coordinate>
    </aol-view>

    <aol-layer-tile>
        <aol-source-osm></aol-source-osm>
    </aol-layer-tile>

    <aol-feature>
        <aol-geometry-point>
            <aol-coordinate [x]="5" [y]="45" [srid]="'EPSG:4326'"></aol-coordinate>
        </aol-geometry-point>
        <aol-style>
            <aol-style-circle [radius]="10">
                <aol-style-stroke [color]="'black'" [width]="2"></aol-style-stroke>
                <aol-style-fill [color]="'green'"></aol-style-fill>
            </aol-style-circle>
        </aol-style>
    </aol-feature>

</aol-map>

i've got this error

No provider for SourceVectorComponent!

Can you guys help me about it?
Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/quentin-ol/angular2-openlayers","title":"quentin-ol/angular2-openlayers","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/quentin-ol/angular2-openlayers"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"No provider for SourceVectorComponent (#60)"}],"action":{"name":"View Issue","url":"https://github.com/quentin-ol/angular2-openlayers/issues/60"}}}

**Comment by bagasprakarso** [comment]
Ok Thanks Quentin 👍
